### ISSUE TITLE
Steps fails with response  [Transporter Error Output]: description length:8507128

### ISSUE THREAD

**Issue by fwigorcferreira** [bitrise-io/steps-deploy-to-itunesconnect-deliver#30]
When trying to upload an item to iTunes connect, the upload fails with the message ` [Transporter Error Output]: description length:8507128` but the error do not stop the build, requiring the developer to manually abort it.

What is the real error reason?

And, how to stop the step after the error?

More details:

```
[07:31:05]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[07:31:08]: Login to iTunes Connect ()
[07:31:10]: Login successful
+--------------------------------------+---------------------------------------------------------------+
|                                        deliver 2.62.1 Summary                                        |
+--------------------------------------+---------------------------------------------------------------+
| username                             |                                 |
| ipa                                  |  |
| skip_screenshots                     | true                                                          |
| skip_metadata                        | true                                                          |
| force                                | true                                                          |
| app_identifier                       |  |
| screenshots_path                     | ./screenshots                                                 |
| metadata_path                        | ./metadata                                                    |
| app_version                          | 1.0                                                           |
| edit_live                            | false                                                         |
| platform                             | ios                                                           |
| skip_binary_upload                   | false                                                         |
| skip_app_version_update              | false                                                         |
| submit_for_review                    | false                                                         |
| automatic_release                    | false                                                         |
| overwrite_screenshots                | false                                                         |
| run_precheck_before_submit           | true                                                          |
| precheck_default_rule_level          | warn                                                          |
| ignore_language_directory_validation | false                                                         |
+--------------------------------------+---------------------------------------------------------------+
[07:31:10]: Making sure the latest version on iTunes Connect matches '1.0' from the ipa file...
[07:31:11]: '1.0' is the latest version on iTunes Connect
[07:31:12]: Uploading binary to iTunes Connect
[07:31:13]: Going to upload updated app to iTunes Connect
[07:31:13]: This might take a few minutes. Please don't interrupt the script.
[07:33:35]: [Transporter Error Output]: description length:8507128
```

**Comment by doomsayer13** [comment]
Thanks for reporting.

**Comment by mooshee** [comment]
Bump.  Seeing the same issue.
```
[12:32:14]: -------------------
[12:32:14]: --- Step: pilot ---
[12:32:14]: -------------------
[12:32:14]: Login to iTunes Connect 
[12:32:18]: Login successful
[12:32:19]: Ready to upload new build to TestFlight (App: 1260726868)...
[12:32:22]: Going to upload updated app to iTunes Connect
[12:32:22]: This might take a few minutes. Please don't interrupt the script.
[12:32:53]: [Transporter Error Output]: description length:6052320```

**Comment by che1404** [comment]
Hi. Same here.

**Comment by viktorbenei** [comment]
This error comes from fastlane/deliver. From the error message it seams that the issue is most likely related to the length of the release notes (set on iTunes Connect).

Please also link your related bitrise.io build URL as we'd need the full log (at least the step's) to be able to provide more help. Additionally if you have some time please create an issue report on fastlane's tracker as the error comes from their tool.

Alternatively of course you can also switch to the Shenzhen based version of this step (**Deploy to iTunes Connect / TestFlight (with Shenzhen)**).

**Comment by sirioz** [comment]
The error is only on bitrise. The same fastlane configuration in local is working without any error.

**Comment by deepeeess** [comment]
I get this issue using Fastlane without bitrise.

**Comment by viktorbenei** [comment]
@deepeeess did you report it on fastlane's github?

**Comment by viktorbenei** [comment]
@sirioz please contact our support via email or through the onsite chat, we'll need the full build log for that. Please also include which version of fastlane you used on your Mac, so that we can debug it and help you as fast as possible :)

**Comment by deepeeess** [comment]
@viktorbenei thank you for your support - the way I resolved this issue was to configure `ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"` in my fastfile as specified in the [documentation for pilot](https://docs.fastlane.tools/actions/pilot/).  A brief inspection of the `--verbose` output was enough to determine there was some problem with the networking.  I'm surprised this option isn't the default to be honest, considering the disproportionate amount of people that are presumably behind NAT firewalls.

**Comment by Sajjon** [comment]
Using Bundler with fastlane `2.97.0`, I too get error `[Transporter Error Output]: description length:4443917`

**Comment by ddsky** [comment]
seeing the same with "latest" version of fastlane and the default -t DAV. Build hangs forever.

**Comment by viktorbenei** [comment]
@Sajjon @ddsky can you please create an issue report at https://discuss.bitrise.io/c/issues/build-issues ? Without those information requested there it's really hard to help.

Locking this thread as it was already closed and not monitored - if you still have an issue please create an issue report at https://discuss.bitrise.io/c/issues/build-issues ! Thank you! :)

**Comment by viktorbenei** [comment]
An alternative solution, if you don't need the extra `deliver` features: use our **Deploy to iTunes Connect - Application Loader** (https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-application-loader) step instead of the deliver one. That uses only official Apple/Xcode tools for the upload.
